# Site
name: TheTensor.Space
title: TheTensor.Space
description: Tools to Tame the Tensor
meta_description: "Tools to Tame the Tensor"
logo: 'assets/images/tensor.png'
favicon: 'assets/images/tensor.png'
paginate: 12
baseurl: 'https://thetensor-space.github.io'
email: 'James.Wilson@ColoState.Edu'
google_analytics: ''
disqus: ''
sharethis: ''

# Authors
authors:
  pete:
    name: Peter A. Brooksbank
    display_name: Pete
    gravatar: 
    email:
    web: 
    twitter:
    description: "Co-Author of TheTensor.Space"
  
  josh:
    name: Joshua F. Maglione
    display_name: Josh
    gravatar: 
    email: 
    web: 
    twitter:
    description: "Co-Author of TheTensor.Space"
  james:
    name: James B. Wilson
    display_name: James
    gravatar: 
    email: James.Wilson@ColoState.Edu
    web: https://www.math.colostate.edu/~jwilson/
    twitter:
    description: "Co-Author of TheTensor.Space"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge